### ISSUE TITLE
Investigate crash issue

### ISSUE THREAD

**Issue by tabreturn** [tabreturn/thonny-py5mode#3]
![YGqdIAd0 png medium](https://user-images.githubusercontent.com/9858145/150143756-bb01bebc-2bf7-478d-b065-e5bd560029ab.png)

Traceback (most recent call last):
  File "C:\Users\alexandre.villares\AppData\Local\Programs\Thonny\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\alexandre.villares\AppData\Local\Programs\Thonny\lib\site-packages\thonny\http://workbench.py", line 1068, in dispatch_from_menu
    dispatch(None)
  File "C:\Users\alexandre.villares\AppData\Local\Programs\Thonny\lib\site-packages\thonny\http://workbench.py", line 994, in dispatch
    handler()
  File "C:\Users\alexandre.villares\AppData\Roaming\Python\Python38\site-packages\thonnycontrib\thonny-py5mode\__init__.py", line 151, in execute_module_mode
    running.get_shell().submit_magic_command(cd_cmd_line + exe_cmd_line)
  File "C:\Users\alexandre.villares\AppData\Local\Programs\Thonny\lib\site-packages\thonny\http://shell.py", line 224, in submit_magic_command
    self.text.submit_command(cmd_line, ("magic",))
  File "C:\Users\alexandre.villares\AppData\Local\Programs\Thonny\lib\site-packages\thonny\http://shell.py", line 408, in submit_command
    self._try_submit_input()
  File "C:\Users\alexandre.villares\AppData\Local\Programs\Thonny\lib\site-packages\thonny\http://shell.py", line 1089, in _try_submit_input
    self._submit_input(submittable_text)
  File "C:\Users\alexandre.villares\AppData\Local\Programs\Thonny\lib\site-packages\thonny\http://shell.py", line 1231, in _submit_input
    get_runner().send_program_input(text_to_be_submitted)
  File "C:\Users\alexandre.villares\AppData\Local\Programs\Thonny\lib\site-packages\thonny\http://running.py", line 313, in send_program_input
    self._proxy.send_program_input(data)
  File "C:\Users\alexandre.villares\AppData\Local\Programs\Thonny\lib\site-packages\thonny\http://running.py", line 972, in send_program_input
    self._send_msg(InputSubmission(data))
  File "C:\Users\alexandre.villares\AppData\Local\Programs\Thonny\lib\site-packages\thonny\http://running.py", line 965, in _send_msg
    self._proc.stdin.write(serialize_message(msg) + "\n")
OSError: [Errno 22] Invalid argument

**Comment by amir-200** [comment]
I am having the same error

**Comment by tabreturn** [comment]
Residual config issue. Delete the Thonny configuration directory (<user>/AppData/Roaming/Thonny).
